name : CI - Test de Base
2
3 on :
4 push :
5 branches : [ main ]
6 pull_request :
7 branches : [ main ]
8
9 jobs :
10 hello :
11 runs - on : ubuntu - latest
12
13 steps :
14 - name : Afficher un message
15 run : echo " CI fonctionne !"
